### ISSUE TITLE
whats about deals or sales

### ISSUE THREAD

**Issue by ihabhamad** [mage2/laravel-ecommerce#110] opened 2017-12-21 02:25 UTC
whats about deals or sale or offers not coupons?

**Comment by ihabhamad** [comment] 2017-12-21 04:31
whats about tags

**Comment by indpurvesh** [comment] 2018-01-06 20:58
I will implement later on some sales & marketing related feature & Coupon Code.

Product tags features comes as a i hope custom module. Currently I am working on Custom module feature and documantation so once it will be done. I will put it on website.[Mage2 Website](http://mage2.website)

This is not a bug so i will close this issue as of now. thanks @ihabhamad

**Closed by indpurvesh** 2018-01-06 20:58 UTC
